contact/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('',views.index, name='index'),
    path('search/',views.search, name='search'),

    # contact (CRUD)
    path('contact/<int:contact_id>/detail/',views.contact, name='contact'),
    path('contact/create/',views.create, name='create'),
    path('contact/<int:contact_id>/update/',views.contact, name='contact'),
    path('contact/<int:contact_id>/delete/',views.contact, name='contact'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return f'{self.name}'


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50,blank=True)
    phone = models.CharField(max_length=50, verbose_name='Mobile')
    email = models.EmailField(max_length = 254,blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture =models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,null=True
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,null=True
    )

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

contact/forms.py
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList
from contact.models import Contact
from typing import Any, Mapping
from django.core.exceptions import ValidationError

class ContactForm(forms.ModelForm):
    # first_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             'class': 'classse-A',
    #             'placeholder':'Write your first name'
    #         }
    #     )
    # )
    first_name = forms.CharField(
        help_text='help Text',
        widget=forms.TextInput(
            attrs={                
                'placeholder':'Write your first name'
            }
        ),
        label='First Name',
    )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['phone'].widget.attrs.update({
            'placeholder':'your phone number'
        })

    class Meta:
        model = Contact
        fields = (
            'first_name',
            'last_name',
            'phone',
            'email',
            'description',
            'category',
        )
        widgets = {            
            'last_name': forms.TextInput(
                attrs={
                    'placeholder': "Write your last name"
                }
            )
        }

    def clean(self) -> dict[str, Any]:
        cleaned_data= self.cleaned_data
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name == last_name:
            error_msg = ValidationError(
                    'first name canot be the same that last name',
                    code='invalid',
                )
            self.add_error('first_name',error_msg)
            self.add_error('last_name',error_msg)

        # self.add_error(
        #     'first_name',
        #     ValidationError(
        #         'Mensagem de erro 2',
        #         code='invalid'
        #     )
        # )
        return super().clean()
    
    def clean_first_name(self):
        data = self.cleaned_data["first_name"]

        if data == 'ABC':
            self.add_error(
                'first_name',
                ValidationError(
                    'Do not input ABC',
                code='invalid'
                )                
            )
        
        return data
    

contact/views/contact_forms.py
from django.shortcuts import render, redirect
from contact.models import Contact
from contact.forms import ContactForm


# Create your views here.

def create(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)  
        context = {
            'form': form     
        }

        if form.is_valid():
            # print('form is valid')
            # contact = form.save(commit=False)
            # contact = form.save(commit=False)
            # contact.show = True
            form.save()
            return redirect('contact:create')

        return render(
            request,
            'contact/create.html',
            context
        )  
     
    context = {
            'form': ContactForm()        
        }
    return render(
        request,
        'contact/create.html',
        context
    )   
    

    

    

contact/views/contact_views.py
from django.shortcuts import render,get_object_or_404, redirect
from contact.models import Contact
from django.db.models import Q
from django.core.paginator import Paginator

# Create your views here.

def index(request):
    contacts = Contact.objects \
        .filter(show=True)\
        .order_by('-id')
    
    paginator = Paginator(contacts,10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj' : page_obj,
        'site_title': 'Contacts'
    }

    return render(
        request,
        'contact/index.html',
        context
    )

def search(request):
    search_value = request.GET.get('q','').strip()

    if search_value == '':
        return redirect('contact:index')  
    

    contacts = Contact.objects \
        .filter(show=True)\
        .filter(
            Q(first_name__icontains=search_value) |
            Q(last_name__icontains=search_value) |
            Q(phone__icontains=search_value) |
            Q(email__icontains=search_value),
        )\
        .order_by('-id')

    paginator = Paginator(contacts,10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)      

    context = {
        'page_obj' : page_obj,
        'site_title': 'search'
    }

    return render(
        request,
        'contact/index.html',
        context
    )

def contact(request, contact_id):
    #single_contact = Contact.objects.filter(pk=contact_id).first()
    single_contact = get_object_or_404(Contact, pk=contact_id,show=True)

    #if single_contact is None:
    #    raise Http404('Contact Not Found!')
 
    context = {
        'contact' : single_contact,
        'site_title': single_contact.first_name

    }

    return render(
        request,
        'contact/contact.html',
        context
    )

contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{contact.first_name}} {{contact.last_name}}
        </h1>
        <p><b>ID:</b> {{contact.id}}</p>
        <p><b>E-mail:</b> {{contact.email}}</p>
        <p><b>Phone:</b> {{contact.phone}}</p>
        <p><b>Created Date:</b> {{contact.created_date}}</p>
        <p><b>Description:</b> {{contact.description}}</p>
        <p><b>Category:</b> {{contact.category}}</p>
    </div>
{% endblock content %}

contact/templates/contact/create.html
{% extends "global/base.html" %}
{% block content %}    
    <div class="form-wrapper">
        <h2>Contact</h2>    
        <form 
          action="{% url "contact:create" %}"
          method="POST"
          enctype="multipart/form-data"
        >
        {% csrf_token %}
          <div class="form-content">
            {% for field in form  %}

                <div class="form-group">
                <label for="{{ field.id_for_label }}">{{field.label}}</label>
                {{field}}
                {{field.errors}}
                {% if field.help_text %}
                    <p class='help-text'>
                        {{field.help_text}}
                    </p>                
                {% endif %}
                </div>

            {% endfor %}
          </div>
    
          <div class="form-content">
            <div class="form-group">
              <button class="btn" type="submit">Send</button>
            </div>
          </div>    
        </form>
      </div>
{% endblock content %}

contact/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %}
{% if page_obj %}
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table caption">
                <h1>Contacts</h1>
            </caption>
            <thead>
                <tr class="table-row tabel-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">First Name</th>
                    <th class="table-header">Last Name</th>
                    <th class="table-header">Phone</th>
                    <th class="table-header">email</th>
                </tr>
            </thead>
            <tbody>
                {% for contact in page_obj  %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a href="{% url "contact:contact" contact.id %}" class="table-link">
                                {{contact.id}}
                            </a>
                        </td>
                        <td class="table-cel">                            
                            {{contact.first_name}}                            
                        </td>
                        <td class="table-cel">                            
                            {{contact.last_name}}                            
                        </td>
                        <td class="table-cel">                            
                            {{contact.phone}}                            
                        </td>
                        <td class="table-cel">                            
                            {{contact.email}}                            
                        </td>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
<div class="single-contact">
    <h1 class="single-contact-name">
        No contact found!
    </h1>    
</div>
{% endif %}
{% endblock content %}